branch-defaults:
  version6.0upgradeBackend:
    environment: Solar-rooftop-env
environment-defaults:
  Solar-rooftop-env:
    branch: null
    repository: null
global:
  application_name: solar-rooftop
  default_ec2_keyname: null
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
