name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Adjust this to match your main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/portfolio:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/portfolio:latest